# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 140, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 220, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Info = QtWidgets.QTextEdit(self.centralwidget)
        self.Info.setGeometry(QtCore.QRect(250, 140, 181, 41))
        self.Info.setObjectName("Info")
        self.Signature = QtWidgets.QTextEdit(self.centralwidget)
        self.Signature.setGeometry(QtCore.QRect(250, 220, 181, 41))
        self.Signature.setObjectName("Signature")
        self.Sign = QtWidgets.QPushButton(self.centralwidget)
        self.Sign.setGeometry(QtCore.QRect(220, 290, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Sign.setFont(font)
        self.Sign.setObjectName("Sign")
        self.GenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.GenerateKeys.setGeometry(QtCore.QRect(390, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.GenerateKeys.setFont(font)
        self.GenerateKeys.setObjectName("GenerateKeys")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Verify = QtWidgets.QPushButton(self.centralwidget)
        self.Verify.setGeometry(QtCore.QRect(370, 290, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Verify.setFont(font)
        self.Verify.setObjectName("Verify")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Information:"))
        self.label_3.setText(_translate("MainWindow", "Signature:"))
        self.Sign.setText(_translate("MainWindow", "Sign"))
        self.GenerateKeys.setText(_translate("MainWindow", "Generate Keys"))
        self.label.setText(_translate("MainWindow", "ECC CIPHER"))
        self.Verify.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
